site_name: BAI2-Reader

# as the mkdocs.yml is in the docs/configs/ subfolder, we need to set the docs_dir to '../'
docs_dir: '../'
site_dir: '../../site'
theme:
  name: material
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          import:
            - https://docs.pydantic.dev/latest/objects.inv
          load_external_modules: true
          options:
            heading_level: 3
            parameter_headings: false
            type_parameter_headings: false
            separate_signature: false
            show_root_heading: true
#            show_symbol_type_toc: false
#            show_symbol_type_heading: false
            show_source: false
            show_bases: false
            docstring_style: google
            extensions:
              - griffe_fieldz:
                  include_inherited: true
nav:
  - Home: index.md
  - Pydantic & Enums: pydantic-and-enums.md
  - Change Log: changelog.md
  - Contribute: contribute.md
